version: "3"

services:
  app:
    build:
      context: .
      target: run
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - spring-demo
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_demo
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    networks:
      - spring-demo
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U -postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:

networks:
  spring-demo:
    driver: bridge